# Generated by Django 2.2.1 on 2019-05-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nn',
            name='code',
            field=models.TextField(max_length=2000),
        ),
    ]
